<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ll</string>
		<string>s</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~L</string>
	<key>name</key>
	<string>LLVM</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>llvm instructions</string>
			<key>match</key>
			<string>\b(add|alloca|and|ashr|bitcast|br|call|eq|exact|extractelement|extractvalue|fadd|fcmp|fdiv|fmul|fpext|fptosi|fptoui|fptrunc|free|frem|fsub|getelementptr|icmp|inbounds|indirectbr|insertelement|insertvalue|inttoptr|invoke|load|lshr|malloc|mul|ne|nsw|nuw|oeq|oge|ogt|ole|olt|one|or|ord|phi|ptrtoint|ret|sdiv|select|sext|sge|sgt|shl|shufflevector|sitofp|sle|slt|srem|store|sub|switch|trunc|udiv|ueq|uge|uge|ugt|ugt|uitofp|ule|ule|ult|ult|une|uno|unreachable|unwind|urem|va_arg|xor|zext)\b</string>
			<key>name</key>
			<string>meta.function-call.llvm</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>llvm keywords</string>
			<key>match</key>
			<string>\b(addrspace|alias|align|alignstack|alwaysinline|appending|asm|blockaddress|byval|c|cc|ccc|coldcc|common|constant|datalayout|declare|default|define|deplibs|dllexport|dllimport|except|extern_weak|external|fastcc|gc|global|hidden|inlinehint|inreg|internal|linkonce|linkonce_odr|metadata|module|naked|nest|noalias|nocapture|noimplicitfloat|noinline|noredzone|noreturn|nounwind|optsize|private|protected|ptx_device|ptx_kernel|readnone|readonly|section|sideeffect|signext|sret|ssp|sspreq|tail|target|thread_local|to|triple|uwtable|volatile|weak|weak_odr|x86_fastcallcc|x86_stdcallcc|zeroext)\b</string>
			<key>name</key>
			<string>keyword.llvm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s([%@][-a-zA-Z$._][-a-zA-Z$._0-9]*)</string>
			<key>name</key>
			<string>variable.llvm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s([%]\d+)</string>
			<key>name</key>
			<string>variable.language.llvm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(i\d+\**)</string>
			<key>name</key>
			<string>storage.type.language.llvm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(!\d+)</string>
			<key>name</key>
			<string>variable.metadata.llvm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>;.*$</string>
			<key>name</key>
			<string>comment.llvm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+\.\d+\b</string>
			<key>name</key>
			<string>constant.numeric.float.llvm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\d+|0(x|X)[a-fA-F0-9]+)\b</string>
			<key>name</key>
			<string>constant.numeric.integer.llvm</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.llvm</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.lvvm</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.llvm</string>
	<key>uuid</key>
	<string>BA22CCD7-4BFB-434E-9D80-79FB1758A944</string>
</dict>
</plist>
